spring:
  application:
    name: book

    datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

    liquibase:
      enabled: true
      change-log: classpath:/db.changelog/db.changelog-master.yaml

    jpa:
      hibernate:
        ddl-auto: none

